### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by sowhatifimlazy** [djkaty/Il2CppInspector#95] opened 2020-10-26 06:03 UTC
Title.

Happens on the game "SCP: Secret Laboratory". Works on other games just fine.

![image](https://user-images.githubusercontent.com/37815394/97138847-7d6b0700-172f-11eb-942f-59f28a36fd3e.png)

**Comment by sowhatifimlazy** [comment] 2020-10-26 06:23
Closing this issue as the binary seems to be packed, woops!

**Comment by djkaty** [comment] 2020-10-28 09:31
Feel free to attach the files anyway, it should detect packed binaries and give you the correct warning, which has not happened in this case!

**Comment by sowhatifimlazy** [comment] 2020-10-29 07:44
global-metadata.dat: http://www.mediafire.com/file/762q0w3qft8mh87/global-metadata.dat/file
GameAssembly.dll: http://www.mediafire.com/file/eef0j59no3s1tkh/GameAssembly.dll/file

Hope this helps, maybe I missed something. 👍

**Comment by NotWaterScriptNhttp** [comment] 2020-11-11 17:38
@sowhatifimlazy did you memory dump the GameAssembly because SCP has obfuscated their GameAssembly? but yeah it does the same for me if no fix then use IL2CPP Dumper it works for SCP

**Comment by djkaty** [comment] 2020-11-11 21:23
Thanks guys. I will fix this, I just don't have much time to work on this right now, as you can see from the outstanding list of issues and the fact 2020.2.1 is so delayed. But I will definitely fix it when I have time; thanks for the reports :)

**Comment by NotWaterScriptNhttp** [comment] 2020-11-12 23:46
no problem

**Comment by StarGate01** [comment] 2020-11-24 02:40
You can also use https://github.com/glmcdona/Process-Dump to dump the unpacked binaries from memory.

**Comment by djkaty** [comment] 2020-11-24 20:43
The files in this issue and #101 are packed with Themida. This is a duplicate of part of #56 where Perfare has requested I integrate the remaining features of Il2CppDumper so that he can retire from working on it. Dealing with packed PE files including Themida is on the roadmap for the next major release version, it should have been out already but unfortunately covid-19 has caused a lot of delays in developing Il2CppInspector lately. I'm getting back to it now.

In the meanwhile as mentioned above I have pushed a commit which informs the user gracefully when a PE file is packed with Themida (or something else unrecognized) rather than crashing with a strange error.

I will close this issue and address it as part of #56 as we complete more items on the roadmap. In the meantime you can use Il2CppDumper to dump these files, though of course you won't get the C++ scaffolding project etc.

**Closed by djkaty** 2020-11-24 20:43 UTC

**Comment by djkaty** [comment] 2020-12-14 02:03
Files packed with Themida can now be processed automatically in the latest commit - enjoy! Let me know if you have any problems with it.
