### ISSUE TITLE
Corrupted float while export

### ISSUE THREAD

**Issue by pandaboy1942** [djkaty/Il2CppInspector#82] opened 2020-09-22 23:28 UTC
when you export a float value, the default float split is `.` character. But the file you export have a float comma split, make whoe code error

**Comment by djkaty** [comment] 2020-09-23 01:28
The decimal separator output will be based on your localization/region settings. For me it's a `.` character. I'm not sure how this is handled in non-English languages. If C always uses `.` for the decimal separator regardless of language, I can change it to always be `.`. Let me know!

**Comment by pandaboy1942** [comment] 2020-09-26 09:08
oh, so decompiler write `,` character cause is based on my region settings?

**Comment by djkaty** [comment] 2020-10-13 06:34
Sorry for the very late response, things have been a bit hectic around here.

I believe this issue is fixed in https://github.com/djkaty/Il2CppInspector/commit/4a75291140d3307837660dd1c09cb0d71717ea54 but could you try it and let me know? Thanks!

**Comment by djkaty** [comment] 2020-10-28 09:37
Closing due to no response from the OP - the issue is assumed fixed, please feel free to re-open the issue if that's not the case.

**Closed by djkaty** 2020-10-28 09:37 UTC
Labels: bug
