### ISSUE TITLE
enum and struct Align problem in IDA

### ISSUE THREAD

**Issue by lifeengines** [djkaty/Il2CppInspector#62] opened 2020-08-29 06:53 UTC
very cool project! 
currently generated enum and struct type has align problem when import to IDA,I found enum's ToString() commented out the size restriction code
` // Don't output " : {underlyingType.Name}" because it breaks C`,
but when import to IDA,the size of enum are important,especially in 64bit.sometimes IDA will align enum member to 8bytes.this make all members of struct after this enum member's offset are wrong,so the final code would be wrong.
sometimes there will generate `  enum ElementType__Enum _Element_k__BackingField;` to struct also made the members' offset goes wrong.
BTW:some "keyword" are not allowed import to IDA,like struct abc{ float near; },the "near" are not allowed by IDA,I think this is IDA's bug,but if Il2CppInspector can avoid generate these member name,This would be very great.

**Comment by djkaty** [comment] 2020-08-29 10:35
Thanks for the kind words and the bug report!

The enum underlying type was commented out recently because Ghidra disassembler support was added and Ghidra is only capable of parsing vanilla C source files - not C++. Does IDA produce the correct offsets in all cases for you if you re-compile Il2CppInspector with the commented out code re-added?

I'll mark this as a low priority bug but it is something I would like to fix. I'll have to think about how, though, while remaining compatible with everything.

We already exclude some IDA keywords (see `CppDeclarationGenerator.CreateNamespace()`) including `__near` and `__far` but not a non-underscored version. `near` is annoyingly defined by windows.h so if you've imported that into IDA it may cause a conflict. In any case, you can add more reserved IDA keywords on line 549 of `CppDeclarationGenerator.cs`. If you have a list of words I should add, that would be great!

**Comment by lifeengines** [comment] 2020-08-29 12:31
as I know ,these word are not allowed inIDA.
 __cppobj
__hidden
__return_ptr
__struct_ptr
__array_ptr
__array_ptr
__noreturn
__pure
__near
__far
__interrupt
__spoils
near
far
__ptr32 
__ptr64 
__restrict 
__shifted

I think this can be add a macro to remaining compatible,like add predefinced marco to common header,like:
`#if defined(_IDA_)
#define ENUM_INT32 :int
#define ENUM_INT16 :short
#else
#define ENUM_INT32
#define ENUM_INT16
#endif`
and then generate code by 
`enum type_1 ENUM_INT16{
}` ,this would under IDA.
even re-added the size restriction code,also has wrong offset in many struct cause by `_Element_k__BackingField` field added. like:
00000028 skillCastType   DCD ?                   ; enum SkillCastType__Enum
0000002C                 DCB ? ; undefined
0000002D                 DCB ? ; undefined
0000002E                 DCB ? ; undefined
0000002F                 DCB ? ; undefined
00000030 _Element_k__BackingField DCQ ?          ; enum ElementType__Enum <- I think this field are compiler generated.
00000038 codeName        DCQ ?                   ; offset
and the align=8byte in this case also made field's member offset wrong,like:
00000078 param1          DCQ ?                   ; offset -> type is float
00000080 param2          DCQ ?                   ; offset
00000088 param3          DCQ ?                   ; offset
00000090 param4          DCQ ?                   ; offset
00000098 param5          DCQ ?                   ; offset
000000A0 param6          DCQ ?                   ; offset
000000A8 param7          DCQ ?                   ; offset-> type is float
000000B0 levelUp         DCQ ?                   ; offset <- here are 4bytes paded.
and I use align=4 to import,also has some same things.
I thinks this is IDA's bug too.
I have a suggestion,the CppType's ToString()'s signature can add a parameter or keep a reference in CppType to reflect generate environment like:
`public override string ToString(AppModel model,string format = "")`
so could generate different code by different configuration.if do this. it can be more convenience for generate code like above mentioned and does not need Macro anymore.

**Comment by djkaty** [comment] 2020-08-29 13:01
I thought about a similar macro approach when I wrote the earlier reply, unfortunately it's not that simple as .NET enum types do not necessarily have a 16 or 32-bit size, they may also derive from `byte`, `ulong` etc. I am not entirely sure how these .NET enum sizes map to what IL2CPP generates - whether it's a 1-to-1 size mapping or not - so I'd have to check.

Anything with `_k__BackingField` is a compiler-generated backing field to a .NET auto-property. It should have the same size as the .NET `enum` type value it represents AFAIK. If it doesn't, that is likely a bug in Il2CppInspector.

Overall this seems like a subtle and somewhat tricky problem. I think the way forward is for me to create a test sample with enums of various underlying types, and then some structs with enum members and auto-properties, compile both 32-bit and 64-bit, and see what IL2CPP, Il2CppInspector and IDA all come up with. This is obviously going to take a while for me to sort out so the solution won't come quickly. I'm glad you found a partial workaround. Thanks for showing the detail, I'll have a think about this and try to get it solved or at least improved for the next release.

What properties/fields from `AppModel` do you think would be useful in `CppType.ToString()`? `WordSize` or something else?

Thanks for the list of IDA keywords, I'll fix that shortly.

**Comment by lifeengines** [comment] 2020-08-29 13:33
I think pass decompile options to CppType can made generate variant code for each decompile type.like enum generate,we can generate code for IDA keep :{underlyingType.Name} and ghidra are not.
when generate header for IDA import.the only import enum size are 4byte,other length like 1,2 will aligned to 4 bytes cause by IL2Cpp's default compile option.so if we pass decompile options to CppType.ToString(),we can generate code for that individually.
for IDA import,we can just map enum to int when UnderlyingType.Size are 1,2,4,or int64 when  UnderlyingType.Size == 8,other cases are keep untouch.
and also we can generate strict code by force struct's pack align size to 1 and use dummy field to keep align pad.like:

struct __declspec(align(1)) test{
bool field1;
char align_pad_1[3];
}
this would made fields' offset strict synced with data in il2cpp.so

**Comment by djkaty** [comment] 2020-08-29 17:15
Alright, I like the `__declspec` idea, this is good. Unfortunately due to the modular nature of the output generators in Il2CppInspector, passing IDA/Ghidra as an option to a C type `ToString()` breaks encapsulation so I think we'll have to find another way - even if that other way is simply passing a boolean option to output the underlying base type or not, or as a format specifier flag.

Thanks for the helpful feedback and suggestions; as said, a fix for this is not going to come right away, but I will resolve it for the next release and post back here when I have an update for you 🙂

**Comment by djkaty** [comment] 2020-09-05 10:22
Hey,

I have now spent some time looking at the problem, but in IDA **when the C++ underlying type restriction is re-applied**, I don't see any problem.

I have added an Enums test (`Il2CppTests/TestSources/Enums.cs`), which you can compile and generate all the output for using TestExplorer. I used the ARM64 build for this example.

We define some enums in C#:

```cs
    public enum EnumOfSize1 : byte ...
    public enum EnumOfSize2 : ushort ...
    public enum EnumOfSize4 : int ...
    public enum EnumOfSize8 : ulong ...
```

and then define a class with some auto-properties:

```cs
    public class ClassWithEnumAutoProperties
    {
        ushort a { get; }
        EnumOfSize1 b { get; }
        ushort c { get; }
        EnumOfSize2 d { get; }
        ushort e { get; }
        EnumOfSize4 f { get; }
        ushort g { get; }
        EnumOfSize8 h { get; }
        ushort i { get; }
    }
```

This gets compiled in IL2CPP like this (C#):

```cs
	public class ClassWithEnumAutoProperties // TypeDefIndex: 2879
	{
		// Fields
		private readonly ushort <a>k__BackingField; // 0x10
		private readonly EnumOfSize1 <b>k__BackingField; // 0x12
		private readonly ushort <c>k__BackingField; // 0x14
		private readonly EnumOfSize2 <d>k__BackingField; // 0x16
		private readonly ushort <e>k__BackingField; // 0x18
		private readonly EnumOfSize4 <f>k__BackingField; // 0x1C
		private readonly ushort <g>k__BackingField; // 0x20
		private readonly EnumOfSize8 <h>k__BackingField; // 0x28
		private readonly ushort <i>k__BackingField; // 0x30
	
		// Properties
		private ushort a { [CompilerGenerated] /* 0x003BD1E8-0x003BD1F8 */ get; } // 0x00B917D4-0x00B917DC 
		private EnumOfSize1 b { [CompilerGenerated] /* 0x003BD1F8-0x003BD208 */ get; } // 0x00B917DC-0x00B917E4 
		private ushort c { [CompilerGenerated] /* 0x003BD208-0x003BD218 */ get; } // 0x00B917E4-0x00B917EC 
		private EnumOfSize2 d { [CompilerGenerated] /* 0x003BD218-0x003BD228 */ get; } // 0x00B917EC-0x00B917F4 
		private ushort e { [CompilerGenerated] /* 0x003BD228-0x003BD238 */ get; } // 0x00B917F4-0x00B917FC 
		private EnumOfSize4 f { [CompilerGenerated] /* 0x003BD238-0x003BD248 */ get; } // 0x00B917FC-0x00B91804 
		private ushort g { [CompilerGenerated] /* 0x003BD248-0x003BD258 */ get; } // 0x00B91804-0x00B9180C 
		private EnumOfSize8 h { [CompilerGenerated] /* 0x003BD258-0x003BD268 */ get; } // 0x00B9180C-0x00B91814 
		private ushort i { [CompilerGenerated] /* 0x003BD268-0x003BD278 */ get; } // 0x00B91814-0x00B9181C 
...
	}
```
These offsets are what we would expect. The C++ output for this type is:

```cpp
struct ClassWithEnumAutoProperties {
    struct ClassWithEnumAutoProperties__Class *klass;
    struct MonitorData *monitor;
    uint16_t _a_k__BackingField;
    enum EnumOfSize1__Enum _b_k__BackingField;
    uint16_t _c_k__BackingField;
    enum EnumOfSize2__Enum _d_k__BackingField;
    uint16_t _e_k__BackingField;
    enum EnumOfSize4__Enum _f_k__BackingField;
    uint16_t _g_k__BackingField;
    enum EnumOfSize8__Enum _h_k__BackingField;
    uint16_t _i_k__BackingField;
};
```

In IDA this is parsed as follows:

```
00000000 ClassWithEnumAutoProperties struc ; (sizeof=0x38, align=0x8, copyof_12961)
00000000 klass           DCQ ?                   ; offset
00000008 monitor         DCQ ?                   ; offset
00000010 _a_k__BackingField DCW ?
00000012 _b_k__BackingField DCB ?                ; enum EnumOfSize1__Enum
00000013                 DCB ? ; undefined
00000014 _c_k__BackingField DCW ?
00000016 _d_k__BackingField DCW ?                ; enum EnumOfSize2__Enum
00000018 _e_k__BackingField DCW ?
0000001A                 DCB ? ; undefined
0000001B                 DCB ? ; undefined
0000001C _f_k__BackingField DCD ?                ; enum EnumOfSize4__Enum
00000020 _g_k__BackingField DCW ?
00000022                 DCB ? ; undefined
00000023                 DCB ? ; undefined
00000024                 DCB ? ; undefined
00000025                 DCB ? ; undefined
00000026                 DCB ? ; undefined
00000027                 DCB ? ; undefined
00000028 _h_k__BackingField DCQ ?                ; enum EnumOfSize8__Enum
00000030 _i_k__BackingField DCW ?
00000032                 DCB ? ; undefined
00000033                 DCB ? ; undefined
00000034                 DCB ? ; undefined
00000035                 DCB ? ; undefined
00000036                 DCB ? ; undefined
00000037                 DCB ? ; undefined
00000038 ClassWithEnumAutoProperties ends
```

which is correct and matches both the IL2CPP metadata offsets and the way Il2CppInspector generates the `struct` for the type. To further verify we can look at the property getters compiled with IL2CPP:

```
il2cpp:0000000000B917FC ; EnumOfSize4__Enum __fastcall ClassWithEnumAutoProperties_get_f(ClassWithEnumAutoProperties *this, MethodInfo *method)
il2cpp:0000000000B917FC ClassWithEnumAutoProperties_get_f
il2cpp:0000000000B917FC ; __unwind {
il2cpp:0000000000B917FC                 LDR             W0, [X0,#0x1C] ; EnumOfSize4 get_f()
il2cpp:0000000000B91800                 RET
il2cpp:0000000000B91800 ; } // starts at B917FC
il2cpp:0000000000B91800 ; End of function ClassWithEnumAutoProperties_get_f
il2cpp:0000000000B91800
il2cpp:0000000000B91804
il2cpp:0000000000B91804 ; =============== S U B R O U T I N E =======================================
il2cpp:0000000000B91804
il2cpp:0000000000B91804
il2cpp:0000000000B91804 ; uint16_t __fastcall ClassWithEnumAutoProperties_get_g(ClassWithEnumAutoProperties *this, MethodInfo *method)
il2cpp:0000000000B91804 ClassWithEnumAutoProperties_get_g
il2cpp:0000000000B91804 ; __unwind {
il2cpp:0000000000B91804                 LDRH            W0, [X0,#0x20] ; UInt16 get_g()
il2cpp:0000000000B91808                 RET
il2cpp:0000000000B91808 ; } // starts at B91804
il2cpp:0000000000B91808 ; End of function ClassWithEnumAutoProperties_get_g
il2cpp:0000000000B91808
il2cpp:0000000000B9180C
il2cpp:0000000000B9180C ; =============== S U B R O U T I N E =======================================
il2cpp:0000000000B9180C
il2cpp:0000000000B9180C
il2cpp:0000000000B9180C ; EnumOfSize8__Enum __fastcall ClassWithEnumAutoProperties_get_h(ClassWithEnumAutoProperties *this, MethodInfo *method)
il2cpp:0000000000B9180C ClassWithEnumAutoProperties_get_h
il2cpp:0000000000B9180C ; __unwind {
il2cpp:0000000000B9180C                 LDR             X0, [X0,#0x28] ; EnumOfSize8 get_h()
il2cpp:0000000000B91810                 RET
```

etc. The values match for every property.

For Ghidra which does not support variable width enums, I will have to apply a solution to this problem, but as far as I can see for IDA it works correctly? Can you guide me to what I'm missing? 🙂

**Comment by lifeengines** [comment] 2020-09-05 11:36
Okay,thanks.I would do the test.but this would happen.here are an example:
```
00000000 ActiveAnimation struc ; (sizeof=0x60, align=0x8, copyof_36893)
00000000 klass           DCQ ?                   ; offset
00000008 monitor         DCQ ?                   ; offset
00000010 m_CachedPtr     DCQ ?                   ; offset
00000018 onFinished      DCQ ?                   ; offset
00000020 eventReceiver   DCQ ?                   ; offset
00000028 callWhenFinished DCQ ?                  ; offset
00000030 mAnim           DCQ ?                   ; offset
00000038 mLastDirection  DCQ ?                   ; enum Direction__Enum
00000040 mDisableDirection DCQ ?                 ; enum Direction__Enum
00000048 mNotify         DCB ?
00000049                 DCB ? ; undefined
0000004A                 DCB ? ; undefined
0000004B                 DCB ? ; undefined
0000004C                 DCB ? ; undefined
0000004D                 DCB ? ; undefined
0000004E                 DCB ? ; undefined
0000004F                 DCB ? ; undefined
00000050 mAnimator       DCQ ?                   ; offset
00000058 mClip           DCQ ?                   ; offset
00000060 ActiveAnimation ends
00000060
```
when member's offset are qword aligned,the compiler use 8bytes(under 64bit).the bool type are the same.but in the C# code,it's not the same,C# compiler would align Enum with same size,regarding which base offset the member is.like:
```
public class ActiveAnimation : MonoBehaviour // TypeDefIndex: 6581
{
    // Fields
    public static ActiveAnimation current; // 0x00
    public List<EventDelegate> onFinished; // 0x18
    [HideInInspector] // 0x00919B04-0x00919B14
    public GameObject eventReceiver; // 0x20
    [HideInInspector] // 0x00919B14-0x00919B24
    public string callWhenFinished; // 0x28
    private Animation mAnim; // 0x30
    private Direction mLastDirection; // 0x38   
    private Direction mDisableDirection; // 0x3C ->this would align with 4bytes
    private bool mNotify; // 0x40 //-> and the bool are align with 8bytes by c# compiler,this would not same as IDA
    private Animator mAnimator; // 0x48
    private string mClip; // 0x50
```

**Comment by lifeengines** [comment] 2020-09-05 13:09
okay,I repeated the Bug.Here are the source of Enums.cs:
```

namespace Il2CppTests.TestSources
{
    // Test to ensure that offsets in structs and classes are calculated correctly for various enum field sizes

#pragma warning disable CS0169
    public enum EnumOfSize1 : byte
    {
        Option1,
        Option2,
        Option3
    }

    public enum EnumOfSize2 : ushort
    {
        Option1,
        Option2,
        Option3
    }

    public enum EnumOfSize4 : int
    {
        Option1,
        Option2,
        Option3
    }

    public enum EnumOfSize8 : ulong
    {
        Option1,
        Option2,
        Option3
    }
    
    public enum EnumOfAuto{
    	Option1,
    	Option2,
    	Option3	
    }

    public struct StructWithEnumFields
    {
        ushort a;
        EnumOfSize1 b;
        ushort c;
        EnumOfSize2 d;
        ushort e;
        EnumOfSize4 f;
        ushort g;
        EnumOfSize8 h;
        ushort i;
        bool a1_1;
        int a1_2;
        bool a2_1;
        bool a2_2;
        int a3;
        EnumOfSize4 a3e1;
        EnumOfSize4 a3e2;
        EnumOfSize4 a3e3;
        bool a4_1;
        bool a4_2;
        EnumOfAuto a5;
        int a7;
        EnumOfAuto a6;
        EnumOfAuto a8;
        bool a9;
        EnumOfAuto a10;
        bool a11;
        EnumOfAuto a12;
        EnumOfAuto a13;
        EnumOfAuto a14;
        ClassWithEnumFields c11;
        bool a16;
        bool a15;
    }

    public class ClassWithEnumFields
    {
        ushort a;
        StructWithEnumFields ptr2;
        ClassWithEnumFields cp1;
        EnumOfSize1 b;
        ushort c;
        EnumOfSize2 d;
        ClassWithEnumFields cp2;
        ushort e;
        StructWithEnumFields ptr3;
        EnumOfSize4 f;
        ushort g;
        EnumOfSize8 h;
        ushort i;
        bool a1_1;
        int a1_2;
        bool a2_1;
        bool a2_2;
        ClassWithEnumFields cp3;
        int a3;
        EnumOfSize4 a3e1;
        EnumOfSize4 a3e2;
        EnumOfSize4 a3e3;
        bool a4_1;
        bool a4_2;
        EnumOfAuto a5;
        int a7;
        EnumOfAuto a6;
        EnumOfAuto a8;
        bool a9;
        EnumOfAuto a10;
        bool a11;
        EnumOfAuto a12;
        StructWithEnumFields ptr1;
        EnumOfAuto a13;
        ClassWithEnumFields cp4;
        EnumOfAuto a14;
        bool a15;
    }

    public class ClassWithEnumAutoProperties
    {
        ushort a { get; }
        EnumOfSize1 b { get; }
        ushort c { get; }
        EnumOfSize2 d { get; }
        ushort e { get; }
        EnumOfSize4 f { get; }
        ushort g { get; }
        EnumOfSize8 h { get; }
        ushort i { get; }
    }
#pragma warning disable CS0169
}
```
when use armv64 to compile this case,would be output:
```
	public class ClassWithEnumFields // TypeDefIndex: 2879
	{
		// Fields
		private ushort a; // 0x10
		private StructWithEnumFields ptr2; // 0x18
		private ClassWithEnumFields cp1; // 0x90
		private EnumOfSize1 b; // 0x98
		private ushort c; // 0x9A
		private EnumOfSize2 d; // 0x9C
		private ClassWithEnumFields cp2; // 0xA0
		private ushort e; // 0xA8
		private StructWithEnumFields ptr3; // 0xB0
		private EnumOfSize4 f; // 0x128
		private ushort g; // 0x12C
		private EnumOfSize8 h; // 0x130
		private ushort i; // 0x138
		private bool a1_1; // 0x13A
		private int a1_2; // 0x13C
		private bool a2_1; // 0x140
		private bool a2_2; // 0x141
		private ClassWithEnumFields cp3; // 0x148
		private int a3; // 0x150
		private EnumOfSize4 a3e1; // 0x154
		private EnumOfSize4 a3e2; // 0x158
		private EnumOfSize4 a3e3; // 0x15C
		private bool a4_1; // 0x160
		private bool a4_2; // 0x161
		private EnumOfAuto a5; // 0x164
		private int a7; // 0x168
		private EnumOfAuto a6; // 0x16C
		private EnumOfAuto a8; // 0x170
		private bool a9; // 0x174
		private EnumOfAuto a10; // 0x178  ->here Enum Of Auto Aligned with 4bytes.
		private bool a11; // 0x17C
		private EnumOfAuto a12; // 0x180
		private StructWithEnumFields ptr1; // 0x188
		private EnumOfAuto a13; // 0x200 ->but here same Enum aligned with 8bytes. this would made IDA goes wrong.
		private ClassWithEnumFields cp4; // 0x208
		private EnumOfAuto a14; // 0x210
		private bool a15; // 0x214
	
		// Constructors
		public ClassWithEnumFields() {} // 0x00B49B8C-0x00B49B8C
	}
```
so,the align would be goes wrong cause by different align logic between C# and C++ compiler.

**Comment by djkaty** [comment] 2020-09-05 15:16
Thanks for reproducing the case. Can you paste in the C++ and IDA output for `ClassWithEnumFields` too please? :)

**Comment by lifeengines** [comment] 2020-09-06 03:34
I packed all the bug related files,you can download from:
[EnumsAlignBug.zip](https://github.com/djkaty/Il2CppInspector/files/5179034/EnumsAlignBug.zip)

I found in the previous example I made a misstake ,sorry for that,but bug does exist.
so I just copy the code that I found the bug to a new Unity project ,repeated the bug again.
all the code is :
```
using System.Collections.Generic;
using UnityEngine;

namespace Il2CppTests.TestSources
{

    public enum Direction
    {
        Reverse = -1,
        Toggle = 0,
        Forward = 1
    }
#pragma warning disable CS0169
    public class ActiveAnimation : MonoBehaviour
    {
        public static ActiveAnimation current; 
        public List<ActiveAnimation> onFinished; 
        [HideInInspector] 
        public GameObject eventReceiver; 
        [HideInInspector] 
        public string callWhenFinished; 
        private Animation mAnim; 
        private Direction mLastDirection; 
        private Direction mDisableDirection; 
        private bool mNotify; 
        private Animator mAnimator; 
        private string mClip; 
    }
#pragma warning disable CS0169
}
```
I compile it with Unity 2019.2.17f1 ,and use both armv7 and arm64,I found the output apk will share
single `global-metadata.dat`.then I use Il2cppInspector to rebuild the class ActiveAnimation in 64bit it
will be:
```
// Image 14: Assembly-CSharp.dll - Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 2046-2048

namespace Il2CppTests.TestSources
{
	public enum Direction // TypeDefIndex: 2047
	{
		Reverse = -1,
		Toggle = 0,
		Forward = 1
	}
	public class ActiveAnimation : MonoBehaviour // TypeDefIndex: 2048
	{
		// Fields
		public static ActiveAnimation current; // 0x00
		public List<ActiveAnimation> onFinished; // 0x18
		[HideInInspector] // 0x00271D74-0x00271D84
		public GameObject eventReceiver; // 0x20
		[HideInInspector] // 0x00271D84-0x00271D94
		public string callWhenFinished; // 0x28
		private Animation mAnim; // 0x30
		private Direction mLastDirection; // 0x38
		private Direction mDisableDirection; // 0x3C
		private bool mNotify; // 0x40
		private Animator mAnimator; // 0x48
		private string mClip; // 0x50
	
		// Constructors
		public ActiveAnimation() {} // 0x0066AD4C-0x0066AD4C
	}
}
```
and the c++ will be:
```
enum Direction__Enum {
    Direction__Enum_Reverse = 0xffffffff,
    Direction__Enum_Toggle = 0x00000000,
    Direction__Enum_Forward = 0x00000001,
};
struct ActiveAnimation {
    struct ActiveAnimation__Class *klass;
    struct MonitorData *monitor;
    void *m_CachedPtr;
    struct List_1_Il2CppTests_TestSources_ActiveAnimation_ *onFinished;
    struct GameObject *eventReceiver;
    struct String *callWhenFinished;
    struct Animation *mAnim;
    enum Direction__Enum mLastDirection;
    enum Direction__Enum mDisableDirection;
    bool mNotify;
    struct Animator *mAnimator;
    struct String *mClip;
};
```
and the IDA:
```
00000000 ActiveAnimation struc ; (sizeof=0x60, align=0x8, copyof_8866)
00000000 klass           DCQ ?                   ; offset
00000008 monitor         DCQ ?                   ; offset
00000010 m_CachedPtr     DCQ ?                   ; offset
00000018 onFinished      DCQ ?                   ; offset
00000020 eventReceiver   DCQ ?                   ; offset
00000028 callWhenFinished DCQ ?                  ; offset
00000030 mAnim           DCQ ?                   ; offset
00000038 mLastDirection  DCQ ?                   ; enum Direction__Enum
00000040 mDisableDirection DCQ ?                 ; enum Direction__Enum -> from here are out synced with c# code
00000048 mNotify         DCB ?
00000049                 DCB ? ; undefined
0000004A                 DCB ? ; undefined
0000004B                 DCB ? ; undefined
0000004C                 DCB ? ; undefined
0000004D                 DCB ? ; undefined
0000004E                 DCB ? ; undefined
0000004F                 DCB ? ; undefined
00000050 mAnimator       DCQ ?                   ; offset
00000058 mClip           DCQ ?                   ; offset
00000060 ActiveAnimation ends
00000060
```
and I does not test the 32bit,I guess 32bit would be okay.

**Comment by djkaty** [comment] 2020-09-07 04:48
I am unable to reproduce this bug.

I copied the .cs file you quoted above as a C# script into a new Unity 2019.3.1f1 project targeting Android/ARM64, built and unzipped the APK, ran Il2CppInspector on it (with the `: {UnderlyingType.Name}` change included) then imported il2cpp-types.h to both IDA 7.2 and 6.8. In both cases the result was the same:

```
00000000 ActiveAnimation struc ; (sizeof=0x58, align=0x8, copyof_8744)
00000000 klass           DCQ ?                   ; offset
00000008 monitor         DCQ ?                   ; offset
00000010 m_CachedPtr     DCQ ?                   ; offset
00000018 onFinished      DCQ ?                   ; offset
00000020 eventReceiver   DCQ ?                   ; offset
00000028 callWhenFinished DCQ ?                  ; offset
00000030 mAnim           DCQ ?                   ; offset
00000038 mLastDirection  DCD ?                   ; enum Direction__Enum
0000003C mDisableDirection DCD ?                 ; enum Direction__Enum
00000040 mNotify         DCB ?
00000041                 DCB ? ; undefined
00000042                 DCB ? ; undefined
00000043                 DCB ? ; undefined
00000044                 DCB ? ; undefined
00000045                 DCB ? ; undefined
00000046                 DCB ? ; undefined
00000047                 DCB ? ; undefined
00000048 mAnimator       DCQ ?                   ; offset
00000050 mClip           DCQ ?                   ; offset
00000058 ActiveAnimation ends
00000058
```

This is the expected behaviour and correctly matches the type.

What version of IDA are you using? Is it possible it has a bug, or that there is some setting in IDA that is affecting this?

**Comment by lifeengines** [comment] 2020-09-07 05:02
seems the problem is ` : {UnderlyingType.Name}`,I use the `{UnderlyingType.Name}` excluded version of Il2cppInspector.

**Comment by djkaty** [comment] 2020-09-07 05:19
Right. I mentioned in https://github.com/djkaty/Il2CppInspector/issues/62#issuecomment-683271731 that I had removed that for Ghidra support and asked if the correct output was produced if we put it back in. You replied:

> even re-added the size restriction code,also has wrong offset in many struct cause by _Element_k__BackingField field added. like:
00000028 skillCastType DCD ? ; enum SkillCastType__Enum
0000002C DCB ? ; undefined
0000002D DCB ? ; undefined
0000002E DCB ? ; undefined
0000002F DCB ? ; undefined
00000030 _Element_k__BackingField DCQ ? ; enum ElementType__Enum <- I think this field are compiler generated.
00000038 codeName DCQ ? ; offset

Is it correct that the offsets are still wrong in some cases when ` : {UnderlyingType.Name}` is re-added or was that a mistake? If correct, please can you provide an example of this so I can try to reproduce it? 🙂

Otherwise, the work to be done is simply to re-add the excluded bit of code for IDA, and #define some macros to make it work correctly with Ghidra.

**Comment by lifeengines** [comment] 2020-09-07 06:00
It's correct.when compile:
```
namespace Il2CppTests.TestSources
{
    
#pragma warning disable CS0169
    public enum SkillCastType : uint 
    {
        Passive = 0,
        Active = 1,
        AutoCast = 2,
        OnDemandPassive = 3,
        AutoCastOnGetHit = 4,
        Custom = 5
    }
    public enum ElementType : int 
    {
        NONE = -1,
        NEUTRAL = 0,
        FIRE = 1,
        WATER = 2,
        THUNDER = 3,
        EARTH = 4
    }
    public interface IBattleObject 
    {
        
        void OnTick();
    }
    public class SkillBase : IBattleObject 
    {
        
        public SkillCastType skillCastType; 

        public bool testb1;
        public ElementType Element
        {
            get;
            set;
        }

        public string codeName; 
        public int level; 
        public string skillNameInCombo; 
        public string customProjectileName; 
        public float channelingTime; 
        public bool noPause; 
        public float cooldown; 
        public float castTime; 
        public float delayActiveTime; 
        public float projectileSpeed; 
        public float range; 
        public float[] param1;
        public float[] param2; 
        public float[] param3; 
        public float[] param4; 
        public float[] param5; 
        public float[] param6; 
        public float[] param7; 
        public int[] levelUp; 
        public float radiusAOE; 
        public int maxTarget; 
        public float manaCost; 
        public bool isAttached; 
        protected int cooldownTick; 
        protected bool isApplying; 
        protected bool isChanneling; 
        public bool IsCallAfterOtherSkill; 
        protected int applyTick; 
        protected int channelingTick; 
        protected int activeTick; 
        protected bool isActived; 
        protected float mskillFactor; 
        public Action OnFinishUseSkillAction; 
        private SkillBase skillInCombo; 
        private bool onDemandPassiveActived; 



        public int LevelIndex1
        {
            get => (int)(Element = ElementType.EARTH); 

        } 
        public bool IsCooldown { get; set; } = true;
    

        public void OnTick()
        {

        }
    }
#pragma warning disable CS0169
    }
```
would produce:
```

struct SkillBase {
    struct SkillBase__Class *klass;
    struct MonitorData *monitor;
    enum SkillCastType__Enum skillCastType;
    bool testb1;
    enum ElementType__Enum _Element_k__BackingField;  <-here made offset wrong
    struct String *codeName;
    int32_t level;
    struct String *skillNameInCombo;
    struct String *customProjectileName;
    float channelingTime;
    bool noPause;
    float cooldown;
    float castTime;
    float delayActiveTime;
    float projectileSpeed;
    float range;
    struct Single__Array *param1;
    struct Single__Array *param2;
    struct Single__Array *param3;
    struct Single__Array *param4;
    struct Single__Array *param5;
    struct Single__Array *param6;
    struct Single__Array *param7;
    struct Int32__Array *levelUp;
    float radiusAOE;
    int32_t maxTarget;
    float manaCost;
    bool isAttached;
    int32_t cooldownTick;
    bool isApplying;
    bool isChanneling;
    bool IsCallAfterOtherSkill;
    int32_t applyTick;
    int32_t channelingTick;
    int32_t activeTick;
    bool isActived;
    float mskillFactor;
    struct Action *OnFinishUseSkillAction;
    struct SkillBase *skillInCombo;
    bool onDemandPassiveActived;
    bool _IsCooldown_k__BackingField;
};
```

**Comment by djkaty** [comment] 2020-09-07 19:39
Ok so the offset of the Element backingField is 0x18 which is correct, but the next item codeName is 0x20 but should be 0x1C, is that correct?

**Comment by djkaty** [comment] 2020-09-10 14:07
I've posted some commits, please let me know if it's working correctly now 👍

**Comment by lifeengines** [comment] 2020-09-11 05:13
thanks very much.it's looks work very well now. and _Element_k__BackingField is not a bug. sorry for my mistake.

**Comment by djkaty** [comment] 2020-09-11 11:23
Awesome! Ultimately I just added back the ": underlyingType" code and made it output different fields for Ghidra to retain C compatibility, I tried various assemblies and couldn't find any different bug.

I'll close the issue now. Feel free to post if you find the problem is not fully solved!

**Closed by djkaty** 2020-09-11 11:23 UTC
Labels: bug
