### ISSUE TITLE
Call vtable ToString method

### ISSUE THREAD

**Issue by badluck13** [djkaty/Il2CppInspector#121] opened 2021-01-07 20:02 UTC
Hi

I really tried my best to call vtable ToString method but nothing seems to work, here is the code so far:

```
void Run()
{
    // If you would like to write to a log file, specify the name above and use il2cppi_log_write()
    il2cppi_log_write("Startup");


    // If you would like to output to a new console window, use il2cppi_new_console() to open one and redirect stdout
    il2cppi_new_console();

    // Place your custom code here

    Il2CppDomain* domain = il2cpp_domain_get();
    size_t size = 0;
    const Il2CppAssembly** assemblies = il2cpp_domain_get_assemblies(domain, &size);

    const Il2CppAssembly* CSharpAssembly = nullptr;
    for (auto i = 0; i < size; ++i) {
        std::cout << assemblies[i]->aname.name << '\n';
        if (std::string(assemblies[i]->aname.name) == "Unity.Model") {
            std::cout << "Found assembly!\n";
            CSharpAssembly = assemblies[i];
        }
    }

    if (CSharpAssembly == nullptr) {
        std::cout << "Error! CSharpAssembly not found!\n";
        //return;
    }

    Il2CppClass* AppModelKlass = il2cpp_class_from_name(CSharpAssembly->image, "Client.Model", "AppModel");

    FieldInfo* instance = il2cpp_class_get_field_from_name(AppModelKlass, "_instance");

    app::AppModel* InGameInstAddr = 0;
    il2cpp_field_static_get_value(instance, &InGameInstAddr);

    app::AppModel* InGameInst = (app::AppModel*)(InGameInstAddr);

    const MethodInfo *m = il2cpp_class_get_method_from_name(AppModelKlass, "get_StaticData", 0);

    auto data = AppModel_get_StaticData(InGameInst, (MethodInfo*)m);

    String(*appModel_ToString)(struct ClientStaticData*, struct MethodInfo*) = (String(*)(struct ClientStaticData*, struct MethodInfo*)) data->klass->vtable.ToString.methodPtr;
    String result = appModel_ToString(data, (MethodInfo*)data->klass->vtable.ToString.method);

    std::cout << result << std::endl;

}
```

And there is the ToString method in the vtable:

```
struct ClientStaticData__Fields {
    struct StaticData__Fields _;
    struct Dictionary_2_System_String_System_String_ *StaticDataLocalization;
    struct Dictionary_2_System_String_System_String_ *ClientLocalization;
};

struct ClientStaticData {
    struct ClientStaticData__Class *klass;
    MonitorData *monitor;
    struct ClientStaticData__Fields fields;
};

struct ClientStaticData__VTable {
    VirtualInvokeData Equals;
    VirtualInvokeData Finalize;
    VirtualInvokeData GetHashCode;
    VirtualInvokeData ToString;
};

struct ClientStaticData__StaticFields {
};

struct ClientStaticData__Class {
    Il2CppClass_0 _0;
    Il2CppRuntimeInterfaceOffsetPair *interfaceOffsets;
    struct ClientStaticData__StaticFields *static_fields;
    const Il2CppRGCTXData *rgctx_data;
    Il2CppClass_1 _1;
    struct ClientStaticData__VTable vtable;
};
```
Any help is very appreciated!

**Comment by djkaty** [comment] 2021-01-07 20:40
Hey badluck13!

Thanks for your message. As you've experienced, the problem is basically that we're not currently providing typed pointers to vtable entries, rather just a generic VirtualInvokeData struct with the method pointer and MethodInfo*. There's a lot of work to be done on C++ scaffolding to make it easier to use - now that it works at all 🙂 - and I will be adding typing to the vtable structs at some point.

I suspect you don't need to use the il2cpp_api functions to accomplish the first part of your code but since I don't have the binary I'm not exactly sure of its structure so I can't say for certain. If `_instance` is a static field of `AppModel` it should be sufficient to just do:

```cpp
auto InGameInst = app::AppModel->static_fields->_instance; // returns app::AppModel*
```

As to the actual vtable call itself, I have to confess I probably don't know any more about this than you do, I generally spend my time maintaining the tool according to user requests and feedback and haven't written anything beyond trivial examples with the C++ output. I skimmed the issues I have in my notes for vtable calling and there are a couple of comments that may be of use:

https://github.com/djkaty/Il2CppInspector/issues/85#issuecomment-699580168

https://github.com/djkaty/Il2CppInspector/issues/71#issuecomment-692255672

My notes also say to write a vtable-calling example in a tutorial so if none of this helps I can try to cook up an example for you when I have a bit of time. Let me know how you get on!

**Comment by badluck13** [comment] 2021-01-07 21:02
Hey @djkaty 

You definitely know way more than me, I'm just hacking around. 

I already tried every comment or code there is in the repo/issues, including the 2 you mentioned. If you have time to get a working example of the vtable function usage it would be a lifesaver. 

Thanks for the Instance tip!

**Comment by djkaty** [comment] 2021-01-07 22:05
Alright, I'll see what I can do as I'd like to get a working example too for a tutorial/guide, it might be two or three days before I get to it though. Do let me know if you get it to work in the meantime :)

**Comment by djkaty** [comment] 2021-01-08 21:19
Whew, well this was an adventure in debugging, disassembly and many windows open, and also led me to fixing two bugs (not related to your issue). So without further ado, here is a working example using Vector3, first calling ToString directly and then via the vtable:

```cpp
void Run()
{
    // Initialize thread data - DO NOT REMOVE
    il2cpp_thread_attach(il2cpp_domain_get());

    il2cppi_new_console();

    // (Call an IL2CPP API function)
    Vector3__Boxed* myVector3 = (Vector3__Boxed*) il2cpp_object_new((Il2CppClass*) *Vector3__TypeInfo);

    // (Call an instance constructor)
    Vector3__ctor(myVector3, 1.0f, 2.0f, 3.0f, nullptr);

    // (Access an instance field)
    std::cout << "x: " << std::to_string(myVector3->fields.x)
        << ", y: " << std::to_string(myVector3->fields.y)
        << ", z: " << std::to_string(myVector3->fields.z)
        << std::endl;

    String* pszVector3 = Vector3_ToString(myVector3, nullptr);

    std::cout << il2cppi_to_string(pszVector3) << std::endl;

    auto vector3_ToString = (String*(*)(Vector3__Boxed*, MethodInfo*)) myVector3->klass->vtable.ToString.methodPtr;
    auto vector3_ToString_MethodInfo = (MethodInfo *) myVector3->klass->vtable.ToString.method;
    auto pszVector3_str = vector3_ToString(myVector3, vector3_ToString_MethodInfo);

    std::cout << il2cppi_to_string(pszVector3_str) << std::endl;
}
```

As far as I can tell, there were three issues with your code:

- Not calling il2cpp_thread_attach at the start
- Using a return type of app::String instead of app::String* (pointer)
- Not calling il2cppi_to_string to convert the app::String* into a std::string for output

The first issue is what was causing access violation exceptions for me. It turns out that deep in ToString() it calls GetThreadStaticData which throws an exception if the thread information isn't initialized. I've added this to the top of Run() in the latest commit (I can't add it to il2cpp-init.h because it runs in a different thread). Note that if you rebuild the project, it's designed so you can re-build in place when the target application is updated so it won't replace your main.cpp, therefore you should add these lines by hand. You shouldn't need to update to the latest commit for this to work.

Thanks for putting me through this, it was really instructive, please do let me know how you get on!

**Comment by badluck13** [comment] 2021-01-08 22:09
Hey @djkaty 

This is awesome it works great! Thank you!

**Comment by djkaty** [comment] 2021-01-09 00:13
Excellent! I've made a note to add this to the tutorial, so I'll go ahead and close the issue now. Hope you find the tool useful :)

**Closed by djkaty** 2021-01-09 00:13 UTC
Labels: help wanted
