### ISSUE TITLE
Could not process IL2CPP image - Unity 2017

### ISSUE THREAD

**Issue by CalinMois** [djkaty/Il2CppInspector#5] opened 2018-01-25 16:12 UTC
Hi, I'm using the dumper on macOS High Sierra. I get the 'Could not process IL2CPP image' message if I try to dump IL2CPP from Unity 2017 builds. It works on Mach-O files though.
Thanks!

**Comment by djkaty** [comment] 2018-02-13 11:58
Hey! Very sorry for the slow reply, I have been in hospital for a couple of weeks.

Could you attach or upload somewhere a copy of the file that won't dump so I can take a look at it? Thanks!

**Comment by CalinMois** [comment] 2018-02-13 14:33
Hello, hope you are well.
You can find the files attached.
Thank you!
[Archive.zip](https://github.com/djkaty/Il2CppInspector/files/1720232/Archive.zip)

**Comment by djkaty** [comment] 2018-02-13 15:04
Downloaded, thank you. I'll try my best to look at it in the next days :)

**Comment by drviver** [comment] 2019-09-19 19:38
I have the same issue. I am on macOS Mojave 10.14.6
[Archive.zip](https://github.com/djkaty/Il2CppInspector/files/3632890/Archive.zip)

**Comment by djkaty** [comment] 2019-10-21 22:45
@drviver - your issue was caused by some lacking support for later Unity 2018 versions in the code. This is fixed (hopefully) in commit https://github.com/djkaty/Il2CppInspector/commit/227eb83b63c3ec93027e522877c835834766c294

@CalinMois - it's taken me 2 years (sorry about that....) but your issue was caused by two problems: a failure to find the function which references the structs needed to analyse the binary, and the fact that the file uses symbol relocations which actually modify data within those structs at load-time. These two issues are fixed in commits https://github.com/djkaty/Il2CppInspector/commit/bebfba4f46012f839b4185e2314346a5b0b1210a and https://github.com/djkaty/Il2CppInspector/commit/c88f058a39d576bb8e0ee4f27809cdd9884691df respectively.

Please re-open the issue if you still have problems!

**Closed by djkaty** 2019-10-21 22:45 UTC

**Comment by CalinMois** [comment] 2019-10-22 09:39
@djkaty You're amazing. The issue is fixed now.
Cheers!
