### ISSUE TITLE
Crash parsing Unity version string

### ISSUE THREAD

**Issue by reyaz006** [djkaty/Il2CppInspector#50] opened 2020-07-10 17:59 UTC
I'm not sure I'm doing everything correctly, but it doesn't seem like there is any other way.

First I'm selecting the metadata file: global-metadata.dat. Then I select the binary file: GameAssembly.dll
Application crashes after a few moments inside the KERNELBASE.dll.

**Comment by djkaty** [comment] 2020-07-10 20:52
Please could you attach the metadata and binary files so that I can reproduce the problem. Thanks!

**Comment by reyaz006** [comment] 2020-07-11 08:56
Here https://mega.nz/file/tmwkkaAQ#XdDTXkRTqCcPbKXNPU3n1mk2dOs0y69jEs84WXW_hzU

**Comment by djkaty** [comment] 2020-07-11 11:08
I wasn't able to reproduce the problem here. Using both the current 2020.1 release, and the latest commit on master, I tried both the CLI and GUI versions on Windows and all four combinations produced the expected results with no crash.

If `global-metadata.dat` and `GameAssembly.dll` are in the same folder, the correct command is:

```
./il2cppinspector -i GameAssembly.dll
```

If you haven't tried both the CLI and GUI, it would be great if you could in case it works on one but not the other so we can narrow down the issue a bit!

**Comment by reyaz006** [comment] 2020-07-11 16:20
Here is the log from CLI version.

```
>il2cppinspector-cli -i Game
Assembly.dll
Il2CppInspector Command-Line Edition
Version 2020.1
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24,1
Container format: PE32+
Container endianness: Little
Architecture word size: 64-bit
Instruction set: x64
Global offset: 0x0000000180000C00
Symbol table search not implemented for this binary format
Required structures acquired from code heuristics. Initialization function: 0x00
00000180001A20
CodeRegistration struct found at 0x0000000180BE8BE0 (file offset 0x00BE73E0)
MetadataRegistration struct found at 0x0000000180BE8CA0 (file offset 0x00BE74A0)

IL2CPP binary version 24,1
Analyze IL2CPP data: 1,23 sec
Create type model: 0,58 sec
Generate C# code: 1,70 sec
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at Il2CppInspector.Cpp.UnityHeaders.UnityHeader..ctor(String headerFilename)
   at Il2CppInspector.Cpp.UnityHeaders.UnityHeader.<>c__DisplayClass16_0.<GetAllHeaders>b__1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Il2CppInspector.Cpp.UnityHeaders.UnityHeader.GuessHeadersForModel(Il2CppModel model)
   at Il2CppInspector.Cpp.CppDeclarationGenerator..ctor(Il2CppModel model, UnityVersion version)
   at Il2CppInspector.Outputs.IDAPythonScript.WriteScriptToFile(String outputFile)
   at Il2CppInspector.CLI.App.Run(Options options)
   at Il2CppInspector.CLI.App.<>c.<Main>b__2_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.CLI.App.Main(String[] args)
Generate IDAPython script: 5,26 sec
```

**Comment by djkaty** [comment] 2020-07-11 16:22
Is there partial output of the .py file? If so can you attach it? Are you positive you sent me the right files?

**Comment by reyaz006** [comment] 2020-07-11 17:25
Files are correct. Here is the only file created by the CLI version. https://mega.nz/file/xjgTkRaT#zJjaSUCAvW-r1jf7WZ1DIy54LROBAB8NEtbexplkCy0

**Comment by djkaty** [comment] 2020-07-11 19:20
Thank you.

What locale/region are you in? What symbols do you use for what in English is the decimal point "." and thousands separator ","? I can't reproduce the problem but the error indicates it does not like the Unity version string, so I'm wondering if it's a language settings issue.

**Comment by reyaz006** [comment] 2020-07-11 19:59
It must be. For me the decimal point is "," and thousands separator is " ". Russian locale.

**Comment by djkaty** [comment] 2020-07-12 01:51
Could you try this build for me and see if it works?

https://drive.google.com/file/d/1zPco6lhjtV4f8sn_4GNkCgXSkAh8SvEZ/view?usp=sharing

That's for Windows, wasn't sure which platform you were using. It is identical to the current master branch in every way except that I changed line 32 of `UnityHeader.cs` to do a culture-invariant parsing of the version string:

```cs
MetadataVersion = double.Parse(bits[0], NumberFormatInfo.InvariantInfo);
```

Let me know how that works out. If it fixes it, I'll make a commit with the change!

**Comment by Skrimel** [comment] 2020-07-12 06:53
I have got same issue now.

**Comment by Skrimel** [comment] 2020-07-12 07:23
> Could you try this build for me and see if it works?
> 
> https://drive.google.com/file/d/1zPco6lhjtV4f8sn_4GNkCgXSkAh8SvEZ/view?usp=sharing
> 
> That's for Windows, wasn't sure which platform you were using. It is identical to the current master branch in every way except that I changed line 32 of `UnityHeader.cs` to do a culture-invariant parsing of the version string:
> 
> ```cs
> MetadataVersion = double.Parse(bits[0], NumberFormatInfo.InvariantInfo);
> ```
> 
> Let me know how that works out. If it fixes it, I'll make a commit with the change!

This works great. Think that is the solution of the issue

**Comment by reyaz006** [comment] 2020-07-12 17:11
That worked from what I see. It generated 2 new files: il2cpp-types.h and ida.py.

**Comment by djkaty** [comment] 2020-07-12 18:14
This issue is fixed in commit https://github.com/djkaty/Il2CppInspector/commit/3c4908c47084eb9891cf2f0f140fde231d9440d1

Thank you both for your help!

**Closed** 2020-07-12 18:15 UTC
Labels: bug
