### ISSUE TITLE
[Feature Request] Generate a C++ header for easy use in DLL's

### ISSUE THREAD

**Issue by DannyParker0001** [djkaty/Il2CppInspector#37] opened 2020-06-17 11:16 UTC
I asked for this in il2cppdumper, prefare didn't want to do it, it wont hurt to ask here.
I don't understand il2cpp enough to implement this myself, but... Here's the idea:
In the il2cppDummyDll you might have:
```cs
void foo(string bar){

}
```

Then (the planned feature) the C++ header
```cpp

// ...
typedef struct Il2CppObject
{
    union
    {
        Il2CppClass *klass;
        Il2CppVTable *vtable;
    };
    MonitorData *monitor;
} Il2CppObject;
//...

// One of the many classes/types exported
namespace System{
    struct String{
        Il2cppObject obj;
        int32_t length;
        char* m_firstChar;

        String(char* value){
            // Function pointer to the virtual address of the System.String constructor that receives a char*
            void (*ctor)(char* value) = (void (*)(char*))0xabcdefg
            ctor(value);
        }
    }
}
// ...
// A Function pointer to the Virtual Address.
void (*foo)(System::String bar) = (void (*)(System::String))(0x1ABCDEF)

```
Which would allow something like
```cpp
#include "Il2cppHeader"

void main(){
System::String str("Hello World");
foo(str);
}

```
Then you compile the project as a DLL, Inject it, and call it.

This is a simple use case for the sake of the example. If it contained every class from every game, you should be able to just write code for it like in mono. Huge potential for being able to mod games but also probably a lot of effort.

**Comment by djkaty** [comment] 2020-06-17 12:04
Very interesting idea. Possible in theory but very difficult (or at least time-consuming) to implement. I suspect there might be so many edge cases that it wouldn't be useful but I could be wrong about that.

We are currently working on code that will make the IDA decompiler output much more pretty and readable. As part of this the Il2Cpp internal struct headers (like Il2CppObject in your example above) will be generated and available as output, so the first part of the problem is actually already in hand.

Generating stubs for all of the functions, class hierarchy, and all the C++ type mappings etc. is a whole other story. We could probably get it up and running for the simple example you illustrated without too much hassle but I think that will quickly become a rabbit hole trying to account for every eventuality.

Il2CppInspector does provide an .NET Reflection-style API that allows you to create output modules, so if you can code in C# you could try to write one that iterates over all of the namespaces and types and outputs stubs like the above with simple C++ type mappings; you can pull out all of the method signatures, virtual address etc. with the API (check out the existing C# output module for an example!). If you do this I'd be very interested to see the results.

Sorry this isn't really the answer you were looking for but I do like the idea so I'll keep it in mind, thanks for reaching out with the suggestion!

**Comment by djkaty** [comment] 2020-06-17 14:40
Update: I saw your fork, you made a pretty good start! Where did you get stuck?

**Comment by DannyParker0001** [comment] 2020-06-19 07:06
Sorry for the late reply, that fork was when I was going to try get the output to work with x64dbg, Ive just mostly given up on trying to make my own il2cppinspector/dumper type thing so I'm a bit burnt out on it for now.
I can try having another crack but I'm pretty inexperienced in C# and programming in general, so making code generator is pretty scary to me.

**Comment by djkaty** [comment] 2020-06-19 11:53
That's understandable, and it's pretty advanced level work so definitely not something an inexperienced developer would have an easy time with. IL2CPP is really complicated and requires a fairly intricate knowledge of a lot of moving parts that I also struggle to understand sometimes; I've definitely been burned out on il2cpp too and sometimes need a break from it!

I definitely would recommend trying to contribute to existing projects and asking questions rather than forging out on your own where possible though. The only reason I made Il2CppInspector is because there were things I wanted to do that Il2CppDumper couldn't, and the code base was such an absolute mess that it was just easier to start again from scratch.

**Comment by djkaty** [comment] 2020-06-22 20:04
@DannyParker0001 We are going to implement this or something similar. It won't be right away but I'm re-opening the issue so you know it will be in progress.

**Comment by djkaty** [comment] 2020-06-27 23:44
Looking at this again with tired eyes. Two questions:

1. Is this just a reformulation of the layout of the normal C++ header output that Il2CppDumper (and the upcoming version of Il2CppInspector) outputs, with function pointer VAs added? Or is there more to it that I'm missing?

2. I assume you're aware that you can't just call a constructor and a method C#-style as shown in your example above. IL2CPP adds extra parameters like MethodInfo* to each method, and calls constructors and such via API init functions which set up various structs, rather than directly. Given that, is this idea still useful? If so can you post a more realistic example so that I can get a really clear idea what I'm supposed to be coding 😂 

Thanks!

**Comment by DannyParker0001** [comment] 2020-06-28 00:25
I wasnt aware the method calls were different, but the principle is:
Construct a header that will contain a definition for a type (Eg system::String) that could be used and passed to functions, for use in DLL Injection.
System.string (The example I use) has the fields
```cs
        Il2cppObject obj;
        int32_t length;
        char* m_firstChar;
```
and a constructor somewhere that takes a `char*`.

I'm really not sure about the implementation, but the result would allow something along the lines of:
(Found in dumper)
```cs
int doFoo(string a, int b)
```
Where you'd need to be able to call doFoo somehow (This is why I suggest DLL injection, then you can just use the virtual address, which you already have)
(The code you write)
```cpp
    #include <il2cppheaders>

    int DoStuffWithFoo(std::string a, int b){
        System::string a(a.c_str());
        doFoo(a, b);
    }

    int main(){
        DoStuffWithFoo("Bar", 0x5);
    }
```
Currently I imagine to achieve this it would be something like
```cpp
    #include<il2cppheaders>
    
    // Haven't checked this code, prob memory leaks (Idk how ownership would work w/ il2cpp)
    int DoStuffWithFoo(std::string a, int b){
        System::string* str = malloc(sizeof(System::string));
        char* chars = malloc(a.length() + 1);
        memcpy(chars, a.c_str(), a.length() + 1);
        // Maybe use the stuff from #39 to get the right Il2cppObject?
        str.length = a.length();
        str.m_firstchar = chars;
        doFoo(str,b);
     }

    int main(){
        DoStuffWithFoo("Bar", 0x5);
    }
    
```
If its not possible to achieve something like it, the general field layout will still be great, its just that also being able to call methods this will basically generate a full C++ API for any given il2cpp game.

**Comment by djkaty** [comment] 2020-06-28 12:20
Thanks for elaborating on that.

Using `System.String` as the running example then, the next major release of Il2CppInspector will output headers for each .NET class type which look like this:

```cpp
struct String {
  struct String__Class *klass;
  struct MonitorData *monitor;
  struct String__Fields fields;
};

struct String__Class {
  struct Il2CppClass_0 _0;
  Il2CppRuntimeInterfaceOffsetPair *interfaceOffsets;
  struct String__StaticFields *static_fields;
  const Il2CppRGCTXData *rgctx_data;
  struct Il2CppClass_1 _1;
  struct String__VTable vtable;
};

struct __declspec(align(8)) String__Fields {
  int32_t m_stringLength;
  uint16_t m_firstChar;
};

struct String__StaticFields {
  struct String * Empty;
};

struct String__Array {
  struct String__Array__Class *klass;
  struct MonitorData *monitor;
  struct Il2CppArrayBounds *bounds;
  il2cpp_array_size_t max_length;
  struct String * vector[32];
};

struct String__VTable {
  VirtualInvokeData Equals;
  VirtualInvokeData Finalize;
  VirtualInvokeData GetHashCode;
  VirtualInvokeData ToString;
  VirtualInvokeData CompareTo;
  VirtualInvokeData Clone;
  VirtualInvokeData GetTypeCode;
  VirtualInvokeData System_IConvertible_ToBoolean;
  VirtualInvokeData System_IConvertible_ToChar;
  VirtualInvokeData System_IConvertible_ToSByte;
  VirtualInvokeData System_IConvertible_ToByte;
  VirtualInvokeData System_IConvertible_ToInt16;
  VirtualInvokeData System_IConvertible_ToUInt16;
  VirtualInvokeData System_IConvertible_ToInt32;
  VirtualInvokeData System_IConvertible_ToUInt32;
  VirtualInvokeData System_IConvertible_ToInt64;
  VirtualInvokeData System_IConvertible_ToUInt64;
  VirtualInvokeData System_IConvertible_ToSingle;
  VirtualInvokeData System_IConvertible_ToDouble;
  VirtualInvokeData System_IConvertible_ToDecimal;
  VirtualInvokeData System_IConvertible_ToDateTime;
  VirtualInvokeData ToString_1;
  VirtualInvokeData System_IConvertible_ToType;
  VirtualInvokeData System_Collections_IEnumerable_GetEnumerator;
  VirtualInvokeData CompareTo_1;
  VirtualInvokeData System_Collections_Generic_IEnumerable_System_Char__GetEnumerator;
  VirtualInvokeData Equals_1;
};
```

This is how the String object is actually stitched together in an IL2CPP application.

Assuming you can get hold of an instance of `String` somewhere, you can access static fields like this:

```cpp
myString.klass->static_fields->Empty    // C#: String.Empty
```

and instance fields like this:

```cpp
myString.fields.firstChar    // C#: myString.firstChar
```

The format of `VirtualInvokeData` has changed once but for almost all versions of IL2CPP it looks like this:

```cpp
typedef struct VirtualInvokeData
{
    Il2CppMethodPointer methodPtr;    // Definition: typedef void (*Il2CppMethodPointer)();
    const MethodInfo* method;
} VirtualInvokeData;
```

Therefore to get the address of a vtable method you would do:

```cpp
void*(*string_CompareTo)() = myString.klass->vtable.CompareTo.methodPtr;
```

For normal non-vtable methods we can of course output the VAs in a header as you previously showed.

The true C++ signature of a method looks like this:

```cpp
int32_t String_CompareTo(struct String * this, struct Object * value, struct MethodInfo *method)
```

Each is a global function (not part of any object) which takes the `this` pointer as the first argument, then the expected arguments, then a `MethodInfo *` (internal il2cpp gubbins).

So the ultimate way to call the method would be something like:
```cpp
int32_t (*string_CompareTo)(struct String *, struct Object *, struct MethodInfo *) = (int32_t (*)(struct String *, struct Object *, struct MethodInfo *)) myString.klass->vtable.CompareTo.methodPtr;
int32_t result = string_CompareTo(myString, ...., myString.klass->vtable.CompareTo.method);
```
(there is also a `VirtActionInvoker` class you can use to call a vtable method by index if you know it; `CompareTo` would be 4 in this example)

All of this assumes that you can actually get an instance of `String` in the first place. For that you need to use `Il2CppObject * il2cpp_codegen_object_new(TypeInfo *klass)` which allocates memory and does the setup for a new object. You can then call the constructor. Assuming we implement #39 so that the exports are available, it will look something like this:

```cpp
String__Class *stringTypeInfo = (String__Class *) 0x12345678; // we're currently outputting this value to the IDAPython script; it could also be included in C++ header output
void (*string_ctor)(String *, Il2CppChar * value, MethodInfo *method) = ... // we're outputting this in C# stubs and IDAPython too

const char16_t *chars = u"hello world!"; // Il2CppChar is uint16_t

String *myString = (String *) il2cpp_codegen_object_new(stringTypeInfo);
string_ctor(myString, chars, NULL);
```

I haven't looked for a while but I assume you can do most or all of this with Il2CppDumper's output already. It will in any case certainly be possible with Il2CppInspector shortly.

So this is the way things currently stand. The conclusions I'm drawing are that what we need is:

- The il2cpp API functions in #39 
- C++ function pointer declarations for every function in the application (eg. string_ctor above)
- C++ TypeInfo* declarations for every class that exists in the application (eg. String__Class *stringTypeInfo above)
- Probably some wrapper/helper methods to simplify the code

Can you confirm that or provide any other feedback on all of this and how it meets or doesn't meet your needs?

I have recently started a blog series on IL2CPP and I'll definitely be covering the intricacies of this down the road, I'm super interested to see if we can get something like this running!

**Comment by DannyParker0001** [comment] 2020-06-28 12:55
"Edit: Hrm, the codegen API functions aren't actually exported. That's a bit of a problem...."
You should be able to use `Il2CppObject* il2cpp_object_new(const Il2CppClass *klass)` since they both call `il2cpp::vm::Object::New(...)`

But yes, thats mostly the goal, once its done, (I'd evaluate this *after* the above has been implemented) but the API isn't OOP for a purely OOP language, so you'd end up with a situation where you're probably going to make a wrapper for every object you consume, eg something like:
```cpp
Namespace system{
    class String{
        String__Class* __field;
        public:

        String(const char16_t* src){
            __field = (String__Class*)(il2cpp_object_new(stringTypeInfo))
            string_ctor(__field, src, NULL);
        }
    }
}
```
So you can simply use it like
```cpp
    system::String(U"hello world");
```
If Il2cppInspector could autogenerate something like it, I would be extremely happy.

**Comment by djkaty** [comment] 2020-06-29 08:06
Alright you can thank me later because I spent the whole of yesterday working on this 😎 . It's a bit of a monster so I posted it in a gist: https://gist.github.com/djkaty/91009a1db1406c0457a35ad452caac73

I created a small Windows standalone x64 Unity project and after no small amount of screwing about was able to successfully inject the above code as a DLL and log the expected result:

```
Startup
H
3.000000
```

The idea is that the vast majority of this code would be auto-generated for you (split into separate files of course), leaving you to simply write the OnAttach() function.

I realize this doesn't solve your "easy" access problem (a la wrapper functions) but IMHO it's a good start. It does at least give you access to all of the types and functions in the binary.

Does this work for you? My thoughts are to implement this in a multi-step process and I'd like your feedback before I embark on this as it is quite a lot of work, but I agree it would be extremely useful to have.

1. First version: output all of the above stuff automatically so you can just write code in OnAttach().
2. Second version: output a Visual Studio project that is setup ready for you to write code
3. Third version: Add "neat" wrappers as per your examples in this PR

I couldn't promise if or when (2) and (3) ever get implemented (by me; other people are welcome to contribute of course) but I'm certainly very interested to implement (1), which will also wrap in #39 .

**Comment by DannyParker0001** [comment] 2020-06-29 13:29
Great job!
"My thoughts are to implement this in a multi-step process" Yep, that's what I suggested before.
Step 1 Would still be a huge milestone!
Step 2 and 3 are both quality of life things that are nice to haves, but could definitely live without.

**Comment by djkaty** [comment] 2020-06-29 15:23
Alright I'll start working on it; don't expect anything for a few weeks though, it's going to take some time. Thanks for helping to flesh out the more precise details with me! 😄

**Comment by djkaty** [comment] 2020-07-02 18:13
The latest commit outputs a C++ header with all the type declarations, in a way that is hopefully somewhat more accurate and complete than Il2CppDumper. None of the method pointers, type addresses or other stuff discussed in this PR are implemented yet.

**Comment by DannyParker0001** [comment] 2020-07-03 03:19
Wow, I didnt expect it to come that quick! Good job.
Some feedback:
Currently the structs look like
```cpp
struct Foo {
  struct Foo__Class *klass;
  struct MonitorData *monitor;
  struct Foo__Fields fields;
};
```
So, to access Foo's fields, you have to write:
```cpp
Foo f;
f.fields.bar;
// rather than just
f.bar
```
Which I can see being very tedious...

And the other potential issue I see is the lack of namespaces, The header for the game I'm working on (Bloons TD 6) is 650K lines, and I tested it with Rust and that game has an 800K line of code header. (I can send you the assemblies/metadata if you wanted them for testing)
You loose all of the organization without the namespaces and create naming conflicts. It would be much nicer with namespaces if as long as it isnt a pain to implement.

Whilst writing this, I also had an idea on `Third version: Add "neat" wrappers as per your examples in this PR`, these could actually be C++/CLI wrappers, Then you can compile a C++/CLI library and consume it in C#, which could actually make an il2cppdumper like 'dummydll' except it'd be functional (Assuming you dll injected the C# program) This isnt available on anything but windows however.

**Comment by djkaty** [comment] 2020-07-03 11:20
Good morning Danny 🙂

I should clarify a little bit what's happening with the development. The current output is deliberately intended to be quite low-level in nature, it's a direct mapping of types to their actual layout in memory. It is basically the same in principle as the output from Il2CppDumper which I believe you were already using for x64dbg if I remember right? So the output should be pretty familiar to you. The main differences are that we are also outputting closed generic types and types from metadata usage references. Crucially, we also take the exact Unity version and compiler into account; both of these variables affect the layout of the types, so while Bloons TD 6 has a nested field object for each type, other games may look like this:

```cpp
struct Foo {
  struct Foo__Class *klass;
  struct MonitorData *monitor;
  int bar;
};
```

Yet others may store `Foo__Fields fields` as a pointer rather than a value. Additionally, there are small variances in layout between some versions of IL2CPP. So the aim here was to just make sure we had as close to 100% accurate as possible mapping of memory layout for each type.

Convenience is something to come later (step 3 from my previous message; right now we are still in step 1), and that includes namespaces. In the meantime, Il2CppInspector will ensure that every type name is unique so you don't need to worry about naming conflicts - there shouldn't be any (if there are, let me know).

I honestly don't know anything about C++/CLI at all except for it being some .NET wrapper-ish language, if you'd like to post that as a separate issue please go ahead (provide some detailed examples and step by step explanations and assume I don't know what C++/CLI is), that sounds really interesting but be warned that will be a very long-term kind of thing for me to look at.

I'll be starting work on the rest of step 1 today.

**Comment by DannyParker0001** [comment] 2020-07-03 13:51
"Yet others may store Foo__Fields fields as a pointer rather than a value. " Oooh ok that makes more sense, I didnt think expect il2cpp to do that. Once you've done step one, I'll try make a quick wrapper in C++/CLI, if it works out I'll make an issue for it.

**Comment by djkaty** [comment] 2020-07-25 15:33
104 commits later...

I have now completed a beta of C++ scaffolding support which generates a complete DLL injection project with all the types, methods and IL2CPP APIs available for the binary. All you should need to do is add your desired code to `Run()` in `main.cpp`.

I'd love it if you could give this a try and let me know how you get on. This work has an extraordinary number of moving parts and requires a lot of coaxing to work on all versions of Unity, I've tried pretty hard to make this the case but there are doubtless numerous remaining bugs, so it's very "beta" right now.

Let me know how it goes!

**Comment by DannyParker0001** [comment] 2020-07-28 13:48
I've had time to have a look at it now, it works great! Would definitely recommend making the project default to having a pre-compiled header. It takes 20-30 seconds to compile on release on my machine, pre-compiled header should help a lot with it.

**Comment by DannyParker0001** [comment] 2020-07-29 22:11
Somebody that I was working with has an older pc, it does not handle the 800K LOC headers in visual studio well. (Constant crashes, 90% CPU usage, unusable when typing). Would be really great to split the header into namespaces.

**Comment by djkaty** [comment] 2020-07-29 23:03
I've been working on the pre-compiled header suggestion, it's really awkward because of some stuff to do with namespaces and the Windows headers but I'm coming up with a workaround.

Splitting up the file is already on the list since you mentioned it earlier, it's a lower priority item. In the latest commit the IDA (and forthcoming, Ghidra) scripts import it as a single file which will make splitting them up a bit more of a chore but I'll do it eventually. Your colleague can split up the headers by taking the first 1500 lines or so (the first 'internal types' section) and putting it in a separate file, then splitting up all the rest arbitrarily to the desired size and making each one include the internal types file.

The current implementation should be considered 'very beta'. I'll be pushing some changes over the next days, I'll post here when I do so :)

**Comment by DannyParker0001** [comment] 2020-07-31 10:24
Just wanted to suggest a couple improvements:
Changing `#define DO_APP_FUNC(a, r, n, p) r (*n) p` to `#define DO_APP_FUNC(a, r, n, p) typedef r (*n) p`
and `#define DO_APP_FUNC(a, r, n, p) r (*n) p` to `#define DO_APP_FUNC(a, r, n, p) typedef r (*n) p`
Made VS go from crashing to displaying 7368 errors. 

I would also recommend putting `init_il2cpp()` in a source file, rather than a header. Currently the way its set up, you `#include <windows>` in `il2cpp-init.h` with many headers disabled which pollutes any source files you include it into (They now MUST `#include <windows>` before they `#include <il2cpp-init.h>`, this will catch a lot of people off guard.)

**Comment by djkaty** [comment] 2020-07-31 16:45
I've already moved init_il2cpp into a source file in my not-yet synced commits, and as I think you must have realized from your edits, changing them to typedefs will turn them into aliases to function pointers and not declarations of the pointers themselves 🙂

**Comment by DannyParker0001** [comment] 2020-08-01 03:09
The compile times I can live with (Since it should only be once right?), What I tried was getting out of memory errors from LLVM and MSVC, so I've given up on it.

**Comment by djkaty** [comment] 2020-08-01 15:08
Okay, the 2nd iteration is now in the master branch so update your clone and have another go!

Be sure to generate the project in a different folder to your current one: some of the filenames and paths have changed and if you mix the old and new projects up it won't compile.

You should be able to just take the contents of `Run()` from your existing project and transplant it into the new one and it should still work.

Most of the changes are in https://github.com/djkaty/Il2CppInspector/commit/5c97202d8ecef0d324688a041b54c302785aaa0c (see the long-form commit message) but I did make some additional tweaks in commits before and after that one. I haven't updated the README.md yet.

Let me know how you get on with that. I'm fairly happy with it now but I'd like feedback from someone using it in the real world before I close the issue 🙂

**Comment by DannyParker0001** [comment] 2020-08-03 22:41
Used it for a bit, as far as I can tell, it works pretty great. I'll make separate issues if I run into any.

**Comment by djkaty** [comment] 2020-08-04 03:52
Awesome! Feel free to do that :) I'm really excited to use this code myself soon. Closing this issue!

**Closed by djkaty** 2020-08-04 03:52 UTC
Labels: enhancement
