### ISSUE TITLE
 "C++ scaffolding header" Your project is perfect! But i need more simples for android platform !

### ISSUE THREAD

**Issue by ianpei** [djkaty/Il2CppInspector#61] opened 2020-08-28 05:35 UTC
"C++ scaffolding header" Your project is perfect! But i need more simples for Android platform !

By try and try hard！

The ndk compiler passed !

But in case runing the project with unity3d so files il2cpp.so &
Other problem happend!

```

long base = baseAddr("libil2cpp.so");
 __android_log_print(ANDROID_LOG_ERROR, "xNative", " %p",base);

 init_il2cpp(base);//mod the oringal api 

__android_log_print(ANDROID_LOG_ERROR, "xNative", " Vector3__TypeInfo %p",Vector3__TypeInfo);
 __android_log_print(ANDROID_LOG_ERROR, "xNative", " il2cpp_object_new%p",il2cpp_object_new);

long a = 0x77a69e8dc8;
long b = 0x77a6041000;
long c = a-b;
 __android_log_print(ANDROID_LOG_ERROR, "xNative", " rollback il2cpp_object_new %p",c);

Vector3__Boxed* myVector3 = (Vector3__Boxed*) il2cpp_object_new((Il2CppClass*) Vector3__TypeInfo);
Vector3__ctor(myVector3, 1.0f, 2.0f, 3.0f, NULL);
float y = myVector3->fields.y;`
```

Log

```
2020-08-28 13:05:40.709 17480-17480/com.ttgame.titanxyz E/xNative:  0x77a5f81000
2020-08-28 13:05:40.713 17480-17480/com.ttgame.titanxyz E/xNative:  Vector3__TypeInfo 0x0
2020-08-28 13:05:40.713 17480-17480/com.ttgame.titanxyz E/xNative:  il2cpp_object_new 0x77a68e8dc8
2020-08-28 13:05:40.713 17480-17480/com.ttgame.titanxyz E/xNative:   rollback il2cpp_object_new 0x9a7dc8
```
    
then

ctrash Vector3__Boxed* myVector3 = (Vector3__Boxed*) il2cpp_object_new((Il2CppClass*) Vector3__TypeInfo);

I mod nothings of the "c++scaffolding"  except  init_il2cpp method for baseadress transfer and .h ref change like "#include "../appdata/il2cpp-types.h"" 

the environment with out  the "c++scaffolding" for my hook works  is running ok & for do "c++scaffolding" running i have colsed all of other working code !

**Comment by djkaty** [comment] 2020-08-29 10:40
`Vector3__TypeInfo` appears to be NULL in the log above. Has it been initialized properly in `init_il2cpp()`? Has Il2CppInspector output `Vector3__TypeInfo` with a non-zero value? Where does the value for `b` come from?

Without having the entire project code and the original il2cpp application, it is pretty hard to say what is going on, but in any case, passing a zero value for `Vector3__TypeInfo` to `il2cpp_object_new` will for sure cause a crash!

**Comment by ianpei** [comment] 2020-08-30 14:38
Before getting to the point，Thanks for your patience very much!

I make a clean unity3dAndroid project with out any develop simple and build a apk, then make a "C++ scaffolding header"  by the tool il2cppinspector gui then fit it to the project.

Hardly to commit i made the source code to a zip file

https://github.com/ianpei/SimpleUnityAndroid/releases/download/Test/SimpleUnityAndroid.zip

The il2cpp lib is  armv7a format.
The main file is native-lib.cpp

If you have a none virtual Android device and have Android studio installed you can run it immediately and debug it directly to the problem.

Oher wise:

You can see source code I have run it and the log is below

```
2020-08-30 22:28:05.982 16017-16017/com.DefaultCompany.NewUnityProject2 E/xNative: the baseAddress is 0xca1c5000
2020-08-30 22:28:05.983 16017-16017/com.DefaultCompany.NewUnityProject2 E/xNative: the Vector3__TypeInfo is 0x0
2020-08-30 22:28:05.983 16017-16017/com.DefaultCompany.NewUnityProject2 E/xNative: the il2cpp_object_new is 0xca2c0a30
    
    --------- beginning of crash
```

Thanks you!

**Comment by ianpei** [comment] 2020-08-30 14:52
By try and try to solve this problem by myself 
I think i lost in this style code #define DO_TYPEDEF(a, n) n ## __TypeInfo = *(n ## __Class**) (baseAddress + a);
Because of my pool c++ basic skil
I need your help

**Comment by djkaty** [comment] 2020-08-30 19:23
The `DO_TYPEDEF` macro you posted above expects as local variable `baseAddress` to be set to the base address of the image. It is a literal replacement, so for example:

```cpp
DO_TYPEDEF(0x1234, SomeItem);
```

will expand to:
```cpp
SomeItem__TypeInfo = (SomeItem__Classs*) (baseAddress + 0x1234);
```

As long as `baseAddress` is set correctly when the code above executes, `SomeItem__TypeInfo` will be set correctly.

**Comment by ianpei** [comment] 2020-08-31 01:24
My guess is similar  as what you said。But after executes, Vector3__TypeInfo also is 0x0。
I hope you can spare a little time to have the demo 3rd marked run !

**Comment by djkaty** [comment] 2020-08-31 05:49
I've downloaded your project files; I've never used Android Studio unfortunately but I looked through your project and through the binary in IDA and I think I know what the problem is.

The implementation of `DO_TYPEDEF` calculates a pointer (`Il2CppClass**`, ie. a pointer to `Il2CppClass*`) and then **reads from that address**. This address is defined in the `.bss` section of the image (meaning it is initialized at runtime by the app). If it hasn't been initialized, it will be set to zero. This means that if you try to access a type that hasn't been initialized yet, you will get this issue.

Types are lazily initialized at the start of each method that uses them via a call to `il2cpp_codegen_initialize_method`. The start of such methods looks like this:

```cpp
// Test1.SimpleStruct Test1.SimpleClass::StaticFunc(Test1.SimpleStruct)
IL2CPP_EXTERN_C IL2CPP_METHOD_ATTR SimpleStruct_tE8816EE61741A4733FD60494CB3DD11FF6C2AFB7  SimpleClass_StaticFunc_mA948E793F220D45CE849393BCBB388FBAAFB5C3D (SimpleStruct_tE8816EE61741A4733FD60494CB3DD11FF6C2AFB7  ___ss0, const RuntimeMethod* method)
{
	static bool s_Il2CppMethodInitialized;
	if (!s_Il2CppMethodInitialized)
	{
		il2cpp_codegen_initialize_method (SimpleClass_StaticFunc_mA948E793F220D45CE849393BCBB388FBAAFB5C3D_MetadataUsageId);
		s_Il2CppMethodInitialized = true;
	}
// ...
```

The value passed is an index into the `MetadataUsages` table:

 ```cpp
void il2cpp_codegen_initialize_method(uint32_t index)
{
    il2cpp::vm::MetadataCache::InitializeMethodMetadata(index);
}
```

By a roundabout way, the final function that does the initialization is:

 ```cpp
void il2cpp::vm::MetadataCache::IntializeMethodMetadataRange(uint32_t start, uint32_t count, const il2cpp::utils::dynamic_array<Il2CppMetadataUsage>& expectedUsages)
```

This range of metadata item indices to initialize (`start` - `start + count`) is derived from the method index - these can be type pointers, methods, string literals or static array fields etc. - and it basically means that if you want to do the initialization yourself, you will need to call `il2cpp_codegen_initialize_method` yourself with an index to a method whose metadata includes the type you want to initialize.

Naturally, this is a big pain in the ass, and luckily you will generally only be working with types that are already initialized.

To verify that this is the problem you can try a couple of things:

1. Create a project using one of the 3D templates - `Vector3` should be initialized by the time your code runs,

or:

2. Try creating a different object, for example a `FileStream` or some other commonly used .NET base class library type. Do not try creating a `String` - il2cpp handles these differently and attempting to create a string using the .NET string class will cause a crash.

Hopefully this is the issue, but you can try it and see.

Thank you very much for the donation, I really appreciate that! When you have completed making a full Android injection project I would be very interested to see it and implement it in Il2CppInspector with your permission, because I want to produce Android hooking project like I currently produce Windows PE DLL injection project, but I have no experience with Cydia Substrate or Android coding in general.

**Comment by ianpei** [comment] 2020-08-31 07:59
Obove you said for me is Android dev for you!

Vector3__TypeInfo 、FileStreamand more i tested is 0x0 all!  the code is called after unity player is resumed even though had a 5s delay!

Im sure function address  is right & can call it  

Im trying other way to get the type adress in running time !

For example by "il2cpp_class_from_name_ptr" function to get it!

But even go, the code will be not elegant away your scaffolding only when you refector the generate code


Can you hide the type address then exposed it by this api at  least exposed it?

Just thinking! 


1、Download Android studio then install it without do anything!
2、The simple is build by unity3d for android platform without any dev but move you folder into and fit the path ref! 
3、Android studio File->open->wating ->run(panel top-right) 
4、the main c++ file is native-lib 

Next space is what you good at!

By try and try,run and run ,test and test,more and more, even discuss with my friend C++ dev good at.


The offset generate by the tool + baseAdress get way in android platform get a wrong result!

I will continue to get a way to write code on a il2cpp

**Comment by djkaty** [comment] 2020-08-31 09:54
I'll check out Android Studio later when I have more time - thanks for the guide :)

In you binary, the virtual range 0x760F60-0x7622C4 (inclusive) contains all of the pointers to the Il2CppClass pointers in the `.bss` section. Read each in turn and see if any are non-zero, eg.

```cpp
for (uintptr_t p = 0x760F60; p <= 0x7622C4; p += sizeof(uintptr_t)) {
  uintptr_t p2 = *(baseAddress + p);
  if (p2 != 0) {
    // Valid TypeInfo found
  }
}
```

There are, as you said, probably ways to get this information via API calls as well, or calls to the internal `il2cpp::vm::` methods (check the il2cpp source code). If this issue turns out to be the same across all Android applications, I will re-factor the scaffolding generation once a solution has been found, to make it as elegant as possible.

**Comment by ianpei** [comment] 2020-08-31 12:09
Thank you! I‘ll make my efforts！
Same time wating your enhancement!

**Comment by ianpei** [comment] 2020-08-31 13:48
Good news !

```
// #define DO_TYPEDEF(a, n) n ## __TypeInfo = *(n ## __Class**) (baseAddress + a);
 #define DO_TYPEDEF(a, n) n ## __TypeInfo = (n ## __Class*) (baseAddress + a);
```
By replace the orignal code above with below & make a delay to call "il2cpp_object_new" as your doc , code pass through and worked well! 

 

But when I try it on real program crash happen also!  

Vector3__TypeInfo not null

Demo is armv7a 

Program is arm64v8a


This is the diff i have known!

Can you give me more suggest what diff between the below il2cpp so file file and demo's  or how to deal this so file in case demo has passed!

https://github.com/ianpei/SimpleUnityAndroid/releases/download/2/libil2cpp.zip

**Comment by djkaty** [comment] 2020-08-31 22:59
I assume when you call `il2cpp_object_new` you have now replaced `Vector3__TypeInfo` with `*Vector3__TypeInfo` yes?

**Comment by ianpei** [comment] 2020-09-01 00:56
Demo  not!
Program not!
Demo pass 
Program not pass

**Comment by djkaty** [comment] 2020-09-01 06:47
The demo app will not pass correctly if you don't de-reference the pointer. You will be overwriting an area of memory containing metadata for other types and it will cause a crash later if any of those types are used.

**Comment by ianpei** [comment] 2020-09-01 09:35
In this case 

Demo havent crash is a coincidence!

Problem recovered to the begin!

**Comment by djkaty** [comment] 2020-09-01 22:33
Yes that's correct unfortunately :( At least I think that is the case.

In order to try and help you further I will have to install Android Studio and start debugging the apps in an emulator; unfortunately I don't really have a great amount of time to do this, it is kind of beyond the scope of the issue tracker here. Have you tried posting on a reverse engineering/hacking forum to see if anyone can help?

One thing is that if the real app is compiled with Unity 2020.2 alpha or later, the way type and method metadata is stored and initialized has been changed significantly and that could be a problem. Other than that I'm kind of out of ideas :(

**Comment by ianpei** [comment] 2020-09-02 05:18
Thank you!
 You have made your best suggest!

**Comment by djkaty** [comment] 2020-09-03 03:12
I'm going to close the issue. I'm sorry that I wasn't able to help you find a solution. If you do solve this problem I'd be really happy for you to post a new comment here 🙂 Good luck!

**Closed by djkaty** 2020-09-03 03:12 UTC
Labels: help wanted

**Comment by mariustoporascu** [comment] 2021-05-30 01:10
Hello katy i don't want to open a new issue so i'll leave a comment here and hopefully will get to you or anyone which has some ideea about the issue i'm having. So i've generated c++ scaffolding proj and took appdata + framework folder as you said in the other issue opened by the same github user. Then i've added the necessary in my android.mk file like so:
`LOCAL_PATH := $(call my-dir)
MAIN_LOCAL_PATH := $(call my-dir)/
include $(CLEAR_VARS)

# Here is the name of your lib.
# When you change the lib name, change also on System.loadLibrary("") under OnCreate method on StaticActivity.java
# Both must have same name
LOCAL_MODULE := unityutils

ALL_SOURCES := c++/32/framework/helpers.cpp \
    c++/32/framework/il2cpp-init.cpp \
    c++/32/framework/pch-il2cpp.cpp \
    Main.cpp \
    Substrate/hde64.c \
    Substrate/SubstrateDebug.cpp \
    Substrate/SubstrateHook.cpp \
    Substrate/SubstratePosixMemory.cpp \
    Substrate/SymbolFinder.cpp \
    KittyMemory/KittyMemory.cpp \
    KittyMemory/MemoryPatch.cpp \
    KittyMemory/MemoryBackup.cpp \
    KittyMemory/KittyUtils.cpp \
    And64InlineHook/And64InlineHook.cpp \
	src/nhr_common.c \
	src/nhr_gz.c \
	src/nhr_map.c \
	src/nhr_memory.c \
	src/nhr_request_method_common.c \
	src/nhr_request_method_get.c \
	src/nhr_request_method_post.c \
	src/nhr_request_private.c \
	src/nhr_request_public.c \
	src/nhr_response.c \
	src/nhr_string.c \
	src/nhr_thread.c \

LOCAL_SRC_FILES := $(ALL_SOURCES)
LOCAL_C_INCLUDES := $(MAIN_LOCAL_PATH)

# Code optimization
# -std=c++17 is required to support AIDE app with NDK
LOCAL_CFLAGS := -Wall -Wno-error=format-security -fvisibility=hidden -ffunction-sections -fdata-sections -w
LOCAL_CFLAGS += -fno-rtti -fexceptions -fpermissive
#-fno-exceptions
LOCAL_CPPFLAGS := -Wall -Wno-error=format-security -fvisibility=hidden -ffunction-sections -fdata-sections -w -Werror -s -std=c++17
LOCAL_CPPFLAGS += -Wno-error=c++11-narrowing -fms-extensions -fno-rtti -fexceptions -fpermissive
#-fno-exceptions
LOCAL_LDFLAGS := -Wl,--gc-sections,--strip-all, -llog
LOCAL_ARM_MODE := arm

LOCAL_LDLIBS := -llog -landroid -lGLESv2 -lz -lc -lm -ldl

include $(BUILD_SHARED_LIBRARY)
`
Rewrote il2cppi_get_base_address() function to this:
`uintptr_t il2cppi_get_base_address() {
    //return (uintptr_t) GetModuleHandleW(L"GameAssembly.dll");
    char filename[0xFF] = {0},
            buffer[1024] = {0};
    FILE *fp = NULL;
    uintptr_t address;
    const char *library = "libil2cpp.so";

    sprintf(filename, OBFUSCATE("/proc/self/maps"));

    fp = fopen(filename, OBFUSCATE("rt"));
    if (fp == NULL) {
        perror(OBFUSCATE("fopen"));
        goto done;
    }

    while (fgets(buffer, sizeof(buffer), fp)) {
        if (strstr(buffer, library)) {
            address = (uintptr_t) strtoul(buffer, NULL, 16);
            goto done;
        }
    }

    done:

    if (fp) {
        fclose(fp);
    }

    return address;
}`
In my main.cpp i have this function running on new thread:
`void *hack_thread(void *) {

   //Check if target lib is loaded
    do {
        sleep(1);
    } while (!isLibraryLoaded(targetLibName) || !methodHit);
    

    //LOGI(OBFUSCATE("%s has been loaded"), (const char *) targetLibName);

#if defined(__aarch64__) //Compile for arm64 lib only
    arm64Funct();

#else //Compile for armv7 lib only. Do not worry about greyed out highlighting code, it still works
    init_il2cpp();
    il2cpp_thread_attach(il2cpp_domain_get());
   arm32Funct();
   #endif

    return NULL;
}`
My ndk-build fails due to undefined symbol error and google hasn't been very helpfull.
`ld: error: undefined symbol: il2cpp_thread_attach
>>> referenced by Main.cpp:0 (C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/src/main/jni\Main.cpp:0)
>>>               C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/unityutils/Main.o:(hack_thread(void*))

ld: error: undefined symbol: il2cpp_domain_get
>>> referenced by Main.cpp:0 (C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/src/main/jni\Main.cpp:0)
>>>               C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/unityutils/Main.o:(hack_thread(void*))

ld: error: undefined symbol: app::GameSendMsg_C2SMarch
>>> referenced by Main.cpp:0 (C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/src/main/jni\Main.cpp:0)
>>>               C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/unityutils/Main.o:(Java_uk_bwmodmenu_modmenu_Preferences_Changes)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/Users/Bumbulica/AppData/Local/Android/Sdk/ndk/22.0.7026061/build//../build/core/build-binary.mk:728: C:/Users/Bumbulica/AndroidStudioProjects/modmenu/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libunityutils.so] Error 1

`
Hopefully anyone has an ideea.

**Comment by mariustoporascu** [comment] 2021-05-30 12:46
Edit: i managed to compile by rewriting the integration. I still have to work on it because i get segmentation fault when calling the function. I tried hooking the function with cydia substrate to see if the function get's called. And it does go inside...might be some issue either with parameters...or something else my brain is incapable of understanding :)).

**Comment by mariustoporascu** [comment] 2021-05-30 12:46
Edit: i managed to compile by rewriting the integration. I still have to work on it because i get segmentation fault when calling the function. I tried hooking the function with cydia substrate to see if the function get's called. And it does go inside...might be some issue either with parameters...or something else my brain is incapable of understanding :)).

**Comment by mariustoporascu** [comment] 2021-05-31 15:00
So actually when you create new object what worked for me was removing * from typeinfo like so:
Auto obj =( obj* )il2cpp object new((il2cpp*)typeinfo)
