### ISSUE TITLE
How to run the IDA script?

### ISSUE THREAD

**Issue by blueboy90780** [djkaty/Il2CppInspector#88] opened 2020-10-05 15:02 UTC
Hi I'm very new and tried searching this everywhere with no answers. Il2CppInspector can generate a python script but what do I need to do to run this script? I tried using the normal python IDE but some libraries can't be imported...

**Comment by djkaty** [comment] 2020-10-07 02:00
Duplicate of #87

**Closed by djkaty** 2020-10-07 02:00 UTC
Labels: duplicate
